name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my repository in the runner
        uses: actions/checkout@v4
      - name: Test code with flake8
        run: pip install flake8 && flake8 main.py
  delivery:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout my repository in the runner
        uses: action/checkout@v4
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/python-api-devops:latest .
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push the image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/python-api-devops:latest

      
